spring:
  application:
    name: ecom
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdatabase
    username: postgres
    password: Shmkau29@
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#   url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: beans, health
  endpoint:
    health:
      show-details: always
    shutdown:
     enabled: true
  info:
    env:
     enabled: true

server:
  shutdown: graceful


info:
  app:
    name: MyNewApp
    description: App built by divyanshi
    version: 1.0.0